name: Instala dependencias con NPM
on:
  push:
    branches: [gh-pages-new]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        with:
          directory: src
      - name: npm install
        uses: argob/poncho@gh-pages-new