name: Instala dependencias con NPM
on:
  push:
    branches: 
      - gh-pages-new
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: c-hive/gha-npm-cache@v1
        uses: c-hive/gha-npm-cache@v1
        with:
          directory: "src"
      - name: npm install
        run: npm install